# Makefile.am --
# $Id: Makefile.am 314 2010-04-17 20:32:33Z ohl $
########################################################################

# Subdirectories to configure
SUBDIRS = doc data

## Data files needed for running CIRCE2
datacirce2dir = $(pkgdatadir)/data
dist_datacirce2_DATA = \
  data/teslage_500.circe \
  data/teslage_500_polavg.circe \
  data/teslagg_200.circe \
  data/teslagg_200_polavg.circe \
  data/teslagg_500.circe \
  data/teslagg_500_polavg.circe \
  data/teslagg_800.circe \
  data/teslagg_800_polavg.circe \
  data/teslage_500.20bins.circe \
  data/teslage_500_polavg.20bins.circe \
  data/teslagg_200.20bins.circe \
  data/teslagg_200_polavg.20bins.circe \
  data/teslagg_500.20bins.circe \
  data/teslagg_500_polavg.20bins.circe \
  data/teslagg_800.20bins.circe \
  data/teslagg_800_polavg.20bins.circe