# Makefile.am --
########################################################################

TOOLS = \
  circe2_compare

TEMPLATES = \
  fill_circe2_template \
  template.circe2_input \
  acc.dat

EXAMPLES = prepare_ilc

EXTRA_DIST = $(TEMPLATES) $(EXAMPLES) $(TOOLS)

examplescirce2dir = $(pkgdatadir)/examples
dist_examplescirce2_DATA = $(TEMPLATES) $(EXAMPLES) $(TOOLS)

